name: Publish to NPM (Trusted)

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest
    environment: npm-publish # Ensure this environment is set up in GitHub repo settings

    permissions:
      contents: read # Required to checkout code
      id-token: write # Required for OIDC/Trusted Publishers
      packages: write # Optional, if you use GitHub Packages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Using Node 20 as it is the current LTS version, best for CI
          node-version: '20' 
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

      - name: Build Library
        # This uses your defined "build" script in package.json
        run: npm run build

      - name: Publish to NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
        
        # This step uses the ID token provided by GitHub OIDC for authorization
        run: npm publish --access public