name: Publish to NPM (Trusted)

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest
    environment: npm-publish # Ensure this environment is set up in GitHub repo settings

    permissions:
      contents: read # Required to checkout code
      id-token: write # Required for OIDC/Trusted Publishers
      packages: write # Optional, if you use GitHub Packages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js for Build and Test
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Using LTS for stability
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

      - name: Build Library
        # This uses your defined "build" script in package.json
        run: npm run build

      - name: Configure NPM Registry for Publishing
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          # NOTE: The 'npm token' required for publishing is handled implicitly by OIDC here.

      - name: Run NPM Publish
        # This is the separate step that executes the shell command after configuration
        run: npm publish --access public